version: '3.8'

services:
  app:
    image: 'vaadin-todo-postgres:latest'
    build:
      context: .
    ports:
      - "8080:8080"
    container_name: vaadin-todo-app
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=asdf
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  db:
    image: 'postgres:15.1-alpine'
    container_name: vaadin-todo-db
    environment:
      - POSTGRES_PASSWORD=asdf